export const SUGGESTIONS = [
  { label: "video-1" },
  { label: "video-2" },
  { label: "video-3" },
  { label: "video-4" },
  { label: "video-5" },
  { label: "video-6" },
  { label: "video-7" },
  { label: "video-8" },
  { label: "video-9" },
  { label: "video-10" },
  { label: "video-11" },
  { label: "video-12" },
  { label: "video-13" },
  { label: "video-14" },
  { label: "video-15" },
  { label: "video-16" },
  { label: "video-17" },
  { label: "video-18" },
  { label: "video-19" },
  { label: "video-20" },
  { label: "video-21" },
  { label: "video-22" },
  { label: "video-23" },
  { label: "video-24" },
  { label: "video-25" },
];
