export const SUGGESTIONS = [
  {
    label: "video-1",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-2",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-3",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-4",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-5",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-6",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-7",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-8",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-9",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-10",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-11",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-12",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-13",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-14",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-15",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-16",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-17",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-18",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-19",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-20",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-21",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-22",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-23",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-24",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
  {
    label: "video-25",
    accountlName: "",
    videoDesc: "",
    videoTitle: "",
    videoMusic: "",
  },
];
